### ISSUE TITLE
ubuntu 17.10 installation

### ISSUE THREAD

**Issue by boraster** [jvkersch/pytsp#5] opened 2018-01-26 18:48 UTC
Hello,

I have been experiencing problem with the pytsp installation. I followed the instruction on the page and didn't get any error during compilation.

I can import pytsp but cannot run Berlin52 example on the page. It looks like there is pytsp package in python library, but none of the classes or functions can be imported as if the package is empty. Pytsp package has only the link "_concorde.cpython-36m-x86_64-linux-gnu.so".

Can you please help me with this problem?

Thanks.

**Comment by jvkersch** [comment] 2018-01-28 22:28
Hi @boraster, sorry to hear about this. Could you clarify what you mean exactly by 

> Pytsp package has only the link "_concorde.cpython-36m-x86_64-linux-gnu.so".

Does the package here refer to the downloaded source code of `pytsp`? If so, what does `ldd _concorde.cpython-36m-x86_64-linux-gnu.so` show?

**Comment by boraster** [comment] 2018-01-29 10:31
Hello @jvkersch,

By 

> Pytsp package has only the link "_concorde.cpython-36m-x86_64-linux-gnu.so". 

, I mean the compiled Pytsp package (with source cloned from your github) within the python3/site-packages.
![pytsp](https://user-images.githubusercontent.com/31406913/35505904-a088dfec-04f8-11e8-89e3-f614730bb513.png)


I renamed "_concorde.cpython-36m-x86_64-linux-gnu.so" to "_concorde.so".
Now, ldd shows the following:

	**linux-vdso.so.1 =>  (0x00007ffc832c3000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007ff8a8083000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007ff8a7ca3000)
	/lib64/ld-linux-x86-64.so.2 (0x00007ff8a8615000)**


>

**Comment by jvkersch** [comment] 2018-02-01 20:01
@boraster I've set up a Ubuntu 17.10 VM but I can't reproduce the problem. I'm on Python 3.6.3, here are the steps I took:
```bash
python3 -m venv pytsp-test-venv
source pytsp-test-venv/bin/activate
git clone https://github.com/jvkersch/pytsp
cd pytsp
pip install -r requirements.txt
tools/build_concorde.sh
python setup.py develop
```
Then `python -m unittest discover -v .` to run the tests.

Does this differ from what you ran? Can you try with these instructions?

**Comment by jvkersch** [comment] 2018-04-25 05:45
@boraster Let me know if you want to follow up on this, in the meantime I'll close this issue.

**Closed by jvkersch** 2018-04-25 05:45 UTC
